apiVersion: v1
kind: ConfigMap
metadata:
  # use this yaml to create a config that kubeturbo will use to connect to the Turbo Server 
  # Provide a value for the config name: and update namespace if needed
  name: turbo-config
  namespace: turbo
data:
  # Update the values for version, turboServer, opsManagerUserName, opsManagerPassword
  # For version, use Turbo Server Version, even when running CWOM
  # The opsManagerUserName requires Turbo administrator role
  # targetConfig is optional. targetName provides better group naming to identify k8s clusters in UI
  # Master nodes are by default not uniquely identified. Use masterNodeDetectors to define by node name patterns using regex or node labels.
  # DaemonSets are identified by default. Use daemonPodDetectors to identify by name patterns using regex or by namespace.
  turbo.config: |-
    {
        "communicationConfig": {
            "serverMeta": {
                "version": "<INSERT TURBONOMIC VERSION>",
                "turboServer": "https://<INSERT TURBONOMIC IP>"
            },
            "restAPIConfig": {
                "opsManagerUserName": "<TURBONOMIC ADMIN USER>",
                "opsManagerPassword": "<TURBONOMIC ADMIN PASSWORD>"
            }
        },
        "targetConfig": {
            "targetName":"turbonomic_GKE_target"
        },
        "masterNodeDetectors": {
           "nodeNamePatterns": [ ".*master.*" ],
           "nodeLabels": [ {"key": "node-role.kubernetes.io/master", "value": ".*"} ]
        }
    }

